# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edist2cpp <- function(A1, A2) {
    .Call(`_secr_edist2cpp`, A1, A2)
}

xydist2cpp <- function(A1, A2) {
    .Call(`_secr_xydist2cpp`, A1, A2)
}

nearestcpp <- function(xy, traps, non_zero) {
    .Call(`_secr_nearestcpp`, xy, traps, non_zero)
}

insidecpp <- function(xy, n1, n2, poly) {
    .Call(`_secr_insidecpp`, xy, n1, n2, poly)
}

naivedcpp <- function(sigma, wt, traps, animals, fn) {
    .Call(`_secr_naivedcpp`, sigma, wt, traps, animals, fn)
}

naivecap3cpp <- function(detect, lambda0, sigma, Tsk, traps, mask, fn) {
    .Call(`_secr_naivecap3cpp`, detect, lambda0, sigma, Tsk, traps, mask, fn)
}

getdenomcpp <- function(fn, miscparm, mask, mm, sigma, z) {
    .Call(`_secr_getdenomcpp`, fn, miscparm, mask, mm, sigma, z)
}

gethcpp <- function(nc1, cc, nmix, nk, ss, mm, PIA, Tsk, hk) {
    .Call(`_secr_gethcpp`, nc1, cc, nmix, nk, ss, mm, PIA, Tsk, hk)
}

makegkPointcpp <- function(detectfn, grain, ncores, gsbval, dist2, miscparm) {
    .Call(`_secr_makegkPointcpp`, detectfn, grain, ncores, gsbval, dist2, miscparm)
}

cappedgkhkcpp <- function(cc, nk, area, D, gk, hk) {
    .Call(`_secr_cappedgkhkcpp`, cc, nk, area, D, gk, hk)
}

makelookupcpp <- function(x) {
    .Call(`_secr_makelookupcpp`, x)
}

nkpointcpp <- function(D, dist2, detect, Tsk, markocc, fn, gsb, miscparm, w2, binomN, grain, ncores) {
    .Call(`_secr_nkpointcpp`, D, dist2, detect, Tsk, markocc, fn, gsb, miscparm, w2, binomN, grain, ncores)
}

pdotpointcpp <- function(xy, traps, dist2, detect, Tsk, markocc, fn, gl0, sig, otherdetpar, miscparm, w2, binomN, grain, ncores) {
    .Call(`_secr_pdotpointcpp`, xy, traps, dist2, detect, Tsk, markocc, fn, gl0, sig, otherdetpar, miscparm, w2, binomN, grain, ncores)
}

fasthistoriescpp <- function(mm, nc, cc, grain, ncores, binomN, indiv, w, ki, gk, hk, density, PIA, Tsk, mbool) {
    .Call(`_secr_fasthistoriescpp`, mm, nc, cc, grain, ncores, binomN, indiv, w, ki, gk, hk, density, PIA, Tsk, mbool)
}

signalhistoriescpp <- function(mm, nc, detectfn, grain, ncores, binomN, w, signal, group, gk, gsbval, dist2, density, PIA, miscparm, mbool) {
    .Call(`_secr_signalhistoriescpp`, mm, nc, detectfn, grain, ncores, binomN, w, signal, group, gk, gsbval, dist2, density, PIA, miscparm, mbool)
}

gethr <- function(nc, fn, start, xy, mask, gsbval, telemscale) {
    .Call(`_secr_gethr`, nc, fn, start, xy, mask, gsbval, telemscale)
}

simplehistoriescpp <- function(mm, nc, cc, grain, ncores, binomN, markocc, firstocc, pID, w, group, gk, hk, density, PIA, Tsk, h, hindex, mbool, telemhr, telemstart) {
    .Call(`_secr_simplehistoriescpp`, mm, nc, cc, grain, ncores, binomN, markocc, firstocc, pID, w, group, gk, hk, density, PIA, Tsk, h, hindex, mbool, telemhr, telemstart)
}

simplehistoriesfxicpp <- function(x, mm, nc, cc, grain, ncores, binomN, w, group, gk, hk, density, PIA, Tsk, h, hindex) {
    .Call(`_secr_simplehistoriesfxicpp`, x, mm, nc, cc, grain, ncores, binomN, w, group, gk, hk, density, PIA, Tsk, h, hindex)
}

Tsightinglikcpp <- function(T, markocc, binomN, Tsk, musk, debug) {
    .Call(`_secr_Tsightinglikcpp`, T, markocc, binomN, Tsk, musk, debug)
}

sightingchatcpp <- function(mm, nc, cc0, grain, ncores, nsim, sightmodel, sumD, area, distrib, binomN, markocc, pID, group, gk0, hk0, density, PIA0, Tsk, pmix) {
    .Call(`_secr_sightingchatcpp`, mm, nc, cc0, grain, ncores, nsim, sightmodel, sumD, area, distrib, binomN, markocc, pID, group, gk0, hk0, density, PIA0, Tsk, pmix)
}

expectedmucpp <- function(nc, cc, Tu, Tm, sightmodel, binomN, markocc, pID, group, gk, hk, pi_density, Nm, PIA, Tsk, h, hindex, a0) {
    .Call(`_secr_expectedmucpp`, nc, cc, Tu, Tm, sightmodel, binomN, markocc, pID, group, gk, hk, pi_density, Nm, PIA, Tsk, h, hindex, a0)
}

simdetectpointcpp <- function(detect, N, cc0, cc, gk0, gk, hk0, hk, PIA0, PIA1, nmix, knownclass, pmix, Tsk, btype, Markov, binomN) {
    .Call(`_secr_simdetectpointcpp`, detect, N, cc0, cc, gk0, gk, hk0, hk, PIA0, PIA1, nmix, knownclass, pmix, Tsk, btype, Markov, binomN)
}

simdetectpolycpp <- function(detect, fn, nmix, btype, Markov, kk, animals, traps, gsb0val, gsb1val, PIA0, PIA1, knownclass, pmix, Tsk, binomN, maxperpoly) {
    .Call(`_secr_simdetectpolycpp`, detect, fn, nmix, btype, Markov, kk, animals, traps, gsb0val, gsb1val, PIA0, PIA1, knownclass, pmix, Tsk, binomN, maxperpoly)
}

simdetectsignalcpp <- function(detect, nmix, fn, cut, gsb0val, PIA0, pmix, knownclass, animals, traps, dist2, Tsk, miscparm) {
    .Call(`_secr_simdetectsignalcpp`, detect, nmix, fn, cut, gsb0val, PIA0, pmix, knownclass, animals, traps, dist2, Tsk, miscparm)
}

expdetectpointcpp <- function(detect, N, cc0, cc, gk0, gk, hk0, hk, PIA0, PIA1, nmix, knownclass, pmix, Tsk, btype, Markov, binomN) {
    .Call(`_secr_expdetectpointcpp`, detect, N, cc0, cc, gk0, gk, hk0, hk, PIA0, PIA1, nmix, knownclass, pmix, Tsk, btype, Markov, binomN)
}

ontransectcpp <- function(xy, transect, n1, n2, tol) {
    .Call(`_secr_ontransectcpp`, xy, transect, n1, n2, tol)
}

alongtransectcpp <- function(xy, transect, n1, n2, tol) {
    .Call(`_secr_alongtransectcpp`, xy, transect, n1, n2, tol)
}

trappingsingle <- function(g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk) {
    .Call(`_secr_trappingsingle`, g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk)
}

trappingmulti <- function(g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk) {
    .Call(`_secr_trappingmulti`, g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk)
}

trappingcapped <- function(g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk) {
    .Call(`_secr_trappingcapped`, g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk)
}

trappingproximity <- function(g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk) {
    .Call(`_secr_trappingproximity`, g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk)
}

trappingcount <- function(g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk) {
    .Call(`_secr_trappingcount`, g0, sigma, z, dist2, Tsk, fn, w2, binomN, bk)
}

trappingpolygon <- function(lambda, sigma, z, npoly, kk, animals, traps, Tsk, fn, w2, binomN, maxperpoly) {
    .Call(`_secr_trappingpolygon`, lambda, sigma, z, npoly, kk, animals, traps, Tsk, fn, w2, binomN, maxperpoly)
}

trappingtransect <- function(lambda, sigma, z, ntransect, kk, animals, traps, Tsk, fn, w2, binomN, maxperpoly) {
    .Call(`_secr_trappingtransect`, lambda, sigma, z, ntransect, kk, animals, traps, Tsk, fn, w2, binomN, maxperpoly)
}

trappingpolygonX <- function(g0, sigma, z, npoly, kk, animals, traps, Tsk, fn, w2, binomN) {
    .Call(`_secr_trappingpolygonX`, g0, sigma, z, npoly, kk, animals, traps, Tsk, fn, w2, binomN)
}

trappingtransectX <- function(lambda, sigma, z, ntransect, kk, animals, traps, Tsk, fn, w2) {
    .Call(`_secr_trappingtransectX`, lambda, sigma, z, ntransect, kk, animals, traps, Tsk, fn, w2)
}

trappingsignal <- function(beta0, beta1, sdS, cut, muN, sdN, sdM, animals, traps, dist2, Tsk, fn) {
    .Call(`_secr_trappingsignal`, beta0, beta1, sdS, cut, muN, sdN, sdM, animals, traps, dist2, Tsk, fn)
}

trappingtelemetry <- function(lambda, sigma, z, animals, ss, fn, w2, binomN, exactn, maxperpoly) {
    .Call(`_secr_trappingtelemetry`, lambda, sigma, z, animals, ss, fn, w2, binomN, exactn, maxperpoly)
}

